function fly1epicutwing11fullxyzpts = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  FLY1EPICUTWING11FULLXYZPTS = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  FLY1EPICUTWING11FULLXYZPTS = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  fly1epicutwing11fullxyzpts = importfile("C:\Users\Tanvi\Dropbox\Summer Project 2020 data\epi_ridge_cut\Fly1\fly1_epi_cutwing1_1\fly1_epi_cutwing1_1_full_xyzpts.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Sep-2020 14:05:31

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 27);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["pt1_X", "pt1_Y", "pt1_Z", "pt2_X", "pt2_Y", "pt2_Z", "pt3_X", "pt3_Y", "pt3_Z", "pt4_X", "pt4_Y", "pt4_Z", "pt5_X", "pt5_Y", "pt5_Z", "pt6_X", "pt6_Y", "pt6_Z", "pt7_X", "pt7_Y", "pt7_Z", "pt8_X", "pt8_Y", "pt8_Z", "pt9_X", "pt9_Y", "pt9_Z"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
fly1epicutwing11fullxyzpts = readtable(filename, opts);

end